# Accept namespaces as args. This requires tilt > v0.22.7

config.define_string_list("namespaces")
cfg = config.parse()

namespaces = cfg.get('namespaces', [])

trigger_file = str(local('mktemp "${TMPDIR:-/tmp}/tilt-kubefwd.XXXXXXXXX"')).strip()

# Creates a button that refreshes the kubefwd without
# requiring new credentials.
local(['./create-refresh-button.sh', trigger_file])

print(os.getcwd())
print('\n\n\n\n\n\n\n\n\n\n\n')

def kubefwd(
  resource_deps=[]
):

  local_resource(
    name='kubefwd:run',
    serve_cmd=['./sudo-kubefwd.sh', trigger_file],
    deps=['sudo-kubefwd.sh', 'run-kubefwd.sh', 'run-kubefwd-internal.sh', 'watch-namespaces.sh'],
    resource_deps=resource_deps,
  )